### ISSUE TITLE
Unable to login to Olympus

### ISSUE THREAD

**Issue by Cassito** [RestComm/Restcomm-Docker#113]
Hello, I am "brand new" to both RestComm and Docker. After some learnings I was able to run Docker (running on an Ubuntu VM). Everything appears to be fine but I am unable to login to Olympus (though RestComm console is ok). 
The command I am using is: docker run  -i -d --name=restcomm -e RCBCONF_STATIC_ADDRESS=192.168.110.162 -e ENVCONFURL="https://raw.githubusercontent.com/RestComm/Restcomm-Docker/master/env_files/restcomm_env_locally.sh" -p 80:80 -p 443:443 -p 9990:9990 -p 5060:5060 -p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp -p 65000-65050:65000-65050/udp -p 8080:8080 -p 8443:8443 restcomm/restcomm:latest

Below the link to the output of the Docker logs 
[RestComm Log.txt](https://github.com/RestComm/Restcomm-Docker/files/1174541/RestComm.Log.txt)

Can you guys help me?

Thanks

Cassio

**Comment by ammendonca** [comment]
Hello @Cassito,

This is likely related to https://github.com/RestComm/Restcomm-Connect/issues/2381. This has been fixed, for a quick fix you can change `<server secure="true">` to `<server secure="false">` in the _/opt/Restcomm-JBoss-AS7/standalone/deployments/olympus.war/resources/xml/olympus.xml_ file. After that your browser will attempt to use ws instead of wss (make sure to clear browser cache so it doesn't get old configuration file).

Also, just noticed your docker command ports are not matching the ones from configuration:

```
Setting SIP_PORT_TCP to 5080
Setting SIP_PORT_TLS to 5081
Setting SIP_PORT_UDP to 5080
Setting SIP_PORT_WS to 5082
Setting SIP_PORT_WSS to 5083
```

You should replace `-p 5060:5060 -p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp` with `-p 5080-5083:5080-5083 -p 5080:5080/udp`.

Closing. For the future, please use [Restcomm group](https://groups.google.com/forum/#!forum/restcomm) for this kind of troubleshooting.

Thanks!

**Comment by Cassito** [comment]
Hello Alexandre,

 

WORKED, many thanks !!!!!!!!!!!!

 

One question to you, where are you based at? Your name sounds Brazilian, just curious as I am Brazilian.

 

Kind regards

 

Cassio

**Comment by ammendonca** [comment]
Glad it worked @Cassito! Sou de Portugal ;)
