### ISSUE TITLE
Improve restcomm-docker as in telscale

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Docker#12]

**Comment by deruelle** [comment]
The goal of this is to improve the end user experience by allowing to have a number of variables preset by default so that everything works out of the box without any tinkering.

The docker image will fetch a configuration file for reading all variables. Those variables can be overriden by providing them via -e as usual. 

The docker image will create a self signed certificate if needed for development environments so that WebRTC on Chrome can work out of the box due to the recent Chrome restrictions for security on WebRTC.

**Comment by leftyb** [comment]
Done with the refactoring of the container scripts. #5
