### ISSUE TITLE
container not running

### ISSUE THREAD

**Issue by rafiql** [RestComm/Restcomm-Docker#26]
I had a running container using below command which suddenly stopped working:
docker run -e VOICERSS_KEY="ad1d87dbe3734e4e8a1cc14e67210d79" --name=restcomm -d -e STATIC_ADDRESS="54.249.98.150" -p 8080:8080 -p 5080:5080 -p 5082:5082 -p 5080:5080/udp -p 65000-65535:65000-65535/udp gvagenas/restcomm:7.3.0

while I am trying create a new one with same command I am getting error 
FATA[0006] Error response from daemon: Cannot start container 2f0dda13f59de50b9a8a1221b2c97c99c4a6bd8a7d5bb2db4ac3154dce8e323c: iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8080 ! -i docker0 -j DNAT --to-destination 172.17.0.6:8080:  (fork/exec /sbin/iptables: cannot allocate memory)

**Comment by leftyb** [comment]
Hi @rafiql ,

Are you using any kind of firewall (e.g. iptables)? If yes please try to disable and test again.
As well have a look [here](https://fralef.me/docker-and-iptables.html)
Please provide which Linux distribution you are using, and docker version ($ docker version). 

Best Regards,
Lefteris.

**Comment by rafiql** [comment]
Thanks Lefteris. It is ubuntu instance in AWS and necessary ports are open. Docker Client version: 1.6.2,  Server version: 1.6.2.

**Comment by rafiql** [comment]
hi there, any other containers are running fine!!!

**Comment by leftyb** [comment]
Hi @rafiql,

It is strange ...
I managed to run the container normally in amazon AMI (amazon Linux) and docker (1.9.1) .
Can you please send the output of :

sudo iptables -L

Looks like the the "Chain DOCKER" is missing.

You must see something like that at the output: 
`DOCKER     all  --  anywhere             anywhere`
`Chain DOCKER (1 references)
target     prot opt source               destination`

Can you please try to restart docker daemon ? 
service docker restart and make sure that `DOCKER     all  --  anywhere   anywhere`
and 

````Chain DOCKER (1 references)

target         prot        opt    source               destination  ``
appears at the 

`sudo iptables -L`

**Comment by rafiql** [comment]
ubuntu@ip-172-31-15-247:~$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination  
DOCKER     all  --  anywhere             anywhere  
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere  
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination  
ACCEPT     udp  --  anywhere             ip-172-17-0-2.ap-northeast-1.compute.internal  udp dpt:65328
ubuntu@ip-172-31-15-247:~$

**Comment by leftyb** [comment]
Hi @rafiql 
Did you restarted docker daemon? 
iptables looks fine. 

Can you please also provide the docker logs.

Thank you.

**Comment by rafiql** [comment]
ubuntu@ip-172-31-15-247:~$ service docker status
docker start/running, process 883
ubuntu@ip-172-31-15-247:~$

**Comment by rafiql** [comment]
root@ip-172-31-15-247:~# service docker stop
docker stop/waiting
root@ip-172-31-15-247:~# service docker status
docker stop/waiting
root@ip-172-31-15-247:~# service docker start
docker start/running, process 27910

**Comment by leftyb** [comment]
Hi @rafiql 

I manage to run normally the same container in both locally (ubuntu) and amazon AMI (amazon Linux), using docker client (1.9) & docker server (1.9). 

Please try to update your docker server & client to a newer version > 1.8 (latest version 1.9).
Please try to stop any other container that you might running because you may have a port conflict there.

Another possible solution is to  try to delete the  old image and pull again.

**Comment by rafiql** [comment]
now i kept other containers stopped. let me update. can you please also advise do i need add any port e.g. 443 in my command?

docker run -e VOICERSS_KEY="ad1d87dbe3734e4e8a1cc14e67210d79" --name=restcomm -d -e STATIC_ADDRESS="54.249.98.150" -p 8080:8080 -p 5080:5080 -p 5082:5082 -p 5080:5080/udp -p 65000-65535:65000-65535/udp gvagenas/restcomm:7.3.0

**Comment by leftyb** [comment]
@rafiql 
Your command looks fine,  but due to RestComm updates we consider tag 7.3.0 as obsolete. You need to use latest versions to properly run RestComm on docker.

We have moved all community docker containers at "restcomm/restcomm" public hub repository. Please delete the old restcomm images that you are using, and pull the new image.
[Here](http://docs.telestax.com/restcomm-docker-quick-start-guide/) you can find all the necessary information.  You will have to update your docker daemon to higher as well (>1.8). 

To pull the new image you need to use:

`docker pull restcomm/restcomm:latest`` 

And to run the new container use :

`docker run  -i -d --name=restcomm-myInstance -v /var/log/restcomm/:/var/log/restcomm/  -e ENVCONFURL="https://raw.githubusercontent.com/RestComm/Restcomm-Docker/master/scripts/restcomm_env_basicAmazon.sh" -p 80:80 -p 443:443 -p 9990:9990 -p 5060:5060 -p 5061:5061 -p 5062:5062 -p 5063:5063 -p 5060:5060/udp -p 65000-65535:65000-65535/udp restcomm/restcomm:latest`

Please contact me, for any further issues you may have. 

*443 port is uses for https self-signed certificate. For basic RestComm RUN  your command is fine.

**Comment by rafiql** [comment]
Docker version is 1.10.

**Comment by leftyb** [comment]
Hi @rafiql ,

Can you please provide the `docker version`

**Comment by rafiql** [comment]
Docker version is 1.10.

**Comment by leftyb** [comment]
Can you please provide for both client and daemon, or both are the same?

Please provide  with the entire output of the command  `docker version`
As well please provide the output for `free -m`
As well please provide the output for  `docker --debug info`

**Comment by rafiql** [comment]
ubuntu@ip-172-31-2-81:~$ docker --debug info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 1.10.0
Storage Driver: devicemapper
 Pool Name: docker-202:1-524478-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.694 GB
 Data Space Total: 107.4 GB
 Data Space Available: 11.53 GB
 Metadata Space Used: 4.85 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-74-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-172-31-2-81
ID: 4I5J:RLA7:J7HP:7467:EXLM:LVWJ:UI4J:3QD2:IUFO:Q773:SPLF:3HIE
WARNING: No swap limit support

ubuntu@ip-172-31-2-81:~$ free -m
             total       used       free     shared    buffers     cached
Mem:          3952        451       3500          0         46        277
-/+ buffers/cache:        127       3824

**Comment by leftyb** [comment]
Hi @rafiql , 

Thank you for the information, but as well I have asked you  to send me the exact output of this  command  `docker version` . Please add this output as well.

Apart from that please send us the logs of the docker daemon itself. Usually in Ubuntu OS the daemon logs are located at Ubuntu - /var/log/upstart/docker.log. 

Then please stop docker daemon and run with debug option `sudo docker daemon -D` and then RUN the container in another terminal window, and please send the output of the DEBUG of docker daemon.

Finally I can see that you are using a 4Gb RAM system and running the command with a big range of RTP ports (the command you are running is mapping 535 ports) so as @hrosa stated at the email send to you, due to memory lack you need to run the container with less RTP ports so please use this command: 

`docker run -e VOICERSS_KEY="ad1d87dbe3734e4e8a1cc14e67210d79" --name=restcomm -d -e STATIC_ADDRESS="54.249.98.150"   -e MEDIASERVER_LOWEST_PORT="65500" -e MEDIASERVER_HIGHEST_PORT="65550" -p 8080:8080 -p 5080:5080 -p 5082:5082 -p 5080:5080/udp -p 65500-65550:65500-65550/udp gvagenas/restcomm:7.3.0`

*Again as explained in previous email, we strongly advice to use the latest restcomm docker image using `restcomm/restcomm:latest`, please see earlier message for more details.

Best Regards.

**Comment by rafiql** [comment]
Please check email

**Comment by s-schumann** [comment]
I had the same issue just now and can confirm correlation of it happening on empty system with 4GB due to the RTP port range. Spawns too many Docker processes for port mapping. Reducing it solved it for me - perhaps a small note should be added here as well: http://www.telestax.com/rapid-webrtc-application-development-with-restcomm-and-docker/
Sebastian

**Comment by leftyb** [comment]
Thank you @s-schumann for the heads-up, we will update the documentation.

**Comment by hamsterksu** [comment]
if you run docker in bridge mode and try to expose a lot of port it will create a lot of docker-proxy processes. it's known bug of docker - https://github.com/docker/docker/issues/8539 
so **solution 1** - use small range or ports **solution 2** - use host mode for docker run `docker run  --net host`

**Comment by s-schumann** [comment]
Thanks @hamsterksu did not know about solution 2 or that it is a known thing in docker. Encountered the issue 1st time. Very useful hint.

**Comment by hamsterksu** [comment]
@s-schumann
**option 3** create custom network overlay for docker and use it for restcomm cluster 
but in this you have setup some gateway in front of cluster

**Comment by deruelle** [comment]
@leftyb has the documentation been update to mention option 2 and 3  ?

**Comment by leftyb** [comment]
Closing issue. Documented as a workaround to use "--net host" to the RUN command in case that a big range of ports is needed.
